---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.10
  driver_config:
    box: vagrant-ubuntu-12.10
    box_url: https://dl.dropboxusercontent.com/u/165709740/boxes/quantal64-vanilla.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
- name: ubuntu-12.04
  driver_config:
    box: vagrant-ubuntu-12.04
    box_url: http://files.vagrantup.com/precise64.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://files.vagrantup.com/lucid64.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list:
  - recipe[chef-solo-search]
  - recipe[znc]
  attributes: {}
- name: source
  run_list:
  - recipe[chef-solo-search]
  - recipe[znc]
  attributes:
    znc:
      install_method: source
